### ISSUE TITLE
Broken install with pip on python 2.x

### ISSUE THREAD

**Issue by tpazderka** [PyCQA/pydocstyle#289]
Pydocstyle does not install properly on python 2.
```bash
$ python --version
Python 2.7.13
$ pip install pydocstyle
Collecting pydocstyle
  Using cached pydocstyle-2.1.0-py2.py3-none-any.whl
Collecting six (from pydocstyle)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting snowballstemmer (from pydocstyle)
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Installing collected packages: six, snowballstemmer, pydocstyle
Successfully installed pydocstyle-2.1.0 six-1.11.0 snowballstemmer-1.2.1
$ pydocstyle
Traceback (most recent call last):
  File "/tmp/test/bin/pydocstyle", line 7, in <module>
    from pydocstyle.cli import main
  File "/tmp/test/local/lib/python2.7/site-packages/pydocstyle/__init__.py", line 1, in <module>
    from .checker import check
  File "/tmp/test/local/lib/python2.7/site-packages/pydocstyle/checker.py", line 12, in <module>
    from .config import IllegalConfiguration
  File "/tmp/test/local/lib/python2.7/site-packages/pydocstyle/config.py", line 10, in <module>
    from configparser import RawConfigParser
ImportError: No module named configparser
$ pip list
pip (9.0.1)
pydocstyle (2.1.0)
setuptools (36.5.0)
six (1.11.0)
snowballstemmer (1.2.1)
wheel (0.30.0)
```

`configparser`  is not installed through `pip`.

**Comment by ntarocco** [comment]
I confirm the issue on Python 2.

Checking the `metadata.json` inside the `whl` package downloaded by `pip`, `configparser` is missing:
```
{
  "classifiers": [
    "Intended Audience :: Developers",
    "Environment :: Console",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License"
  ],
  "description_content_type": "UNKNOWN",
  "extensions": {
    "python.commands": {
      "wrap_console": {
        "pydocstyle": "pydocstyle.cli:main"
      }
    },
    "python.details": {
      "contacts": [
        {
          "email": "amir@rachum.com",
          "name": "Amir Rachum",
          "role": "author"
        }
      ],
      "document_names": {
        "description": "DESCRIPTION.rst"
      },
      "project_urls": {
        "Home": "https://github.com/PyCQA/pydocstyle/"
      }
    },
    "python.exports": {
      "console_scripts": {
        "pydocstyle": "pydocstyle.cli:main"
      }
    }
  },
  "extras": [],
  "generator": "bdist_wheel (0.29.0)",
  "keywords": [
    "pydocstyle",
    "PEP",
    "257",
    "pep257",
    "PEP",
    "8",
    "pep8",
    "docstrings"
  ],
  "license": "MIT",
  "metadata_version": "2.0",
  "name": "pydocstyle",
  "run_requires": [
    {
      "requires": [
        "six",
        "snowballstemmer"
      ]
    }
  ],
  "summary": "Python docstring style checker",
  "version": "2.1.0"
}
```

See `pip -v install pydocstyle` log:
```
Collecting pydocstyle
  1 location(s) to search for versions of pydocstyle:
  * https://pypi.python.org/simple/pydocstyle/
  Getting page https://pypi.python.org/simple/pydocstyle/
  Looking up "https://pypi.python.org/simple/pydocstyle/" in the cache
  Current age based on date: 913
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The cached response is "stale" with no etag, purging
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/pydocstyle/ HTTP/1.1" 200 888
  Updating cache with response from "https://pypi.python.org/simple/pydocstyle/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/pydocstyle/
    Found link https://pypi.python.org/packages/21/1d/2afb75448d496a1a53815a5e2edd5fc8828eff6730ae29ce18801d2d4077/pydocstyle-2.1.0-py2.py3-none-any.whl#md5=eeddf1eb4b069cb0a6ad8ff8c2cc07d9 (from https://pypi.python.org/simple/pydocstyle/), version: 2.1.0
    Found link https://pypi.python.org/packages/32/6a/b500937a4098be1e890f34590219ee6998f02a0256ab228969494b64fbca/pydocstyle-2.1.0.tar.gz#md5=291d7b3df72766aecba2683f87dde9b3 (from https://pypi.python.org/simple/pydocstyle/), version: 2.1.0
    Found link https://pypi.python.org/packages/3a/ae/e00f314bdf4654329aab3f0443cb5b213c79cc25002e49a2f8cbf8a09936/pydocstyle-1.0.0.zip#md5=74a42c1c8148f80c8f2931b615b54a24 (from https://pypi.python.org/simple/pydocstyle/), version: 1.0.0
    Found link https://pypi.python.org/packages/42/ae/67a288482857b728f2e84db2e5f48c6e5d6a9d44ba4eefbaf63e42a88e54/pydocstyle-1.1.0-py2.py3-none-any.whl#md5=1fa964c5625aaba2ae27319fb16417db (from https://pypi.python.org/simple/pydocstyle/), version: 1.1.0
    Found link https://pypi.python.org/packages/5c/ca/0849f5a833575eb43c57dc5a40ca825615b234d161cc69bc9ce5867d7169/pydocstyle-2.0.0-py2.py3-none-any.whl#md5=fabd0b1aa293481a466eb0366f32bfe7 (from https://pypi.python.org/simple/pydocstyle/), version: 2.0.0
    Found link https://pypi.python.org/packages/64/d7/94b423691e720d96ff34014b67f8dfb8ab7b434dfc338f8d178543c61932/pydocstyle-1.1.0.zip#md5=f52fa81219abb856deab9af0df270227 (from https://pypi.python.org/simple/pydocstyle/), version: 1.1.0
    Found link https://pypi.python.org/packages/b0/33/52e2fa5662fbb2a8bc9bdfe31327cd58c2f856b31851b73fc5baf86a2a14/pydocstyle-2.0.0.zip#md5=2be57712e2743d23949bafed957d8c86 (from https://pypi.python.org/simple/pydocstyle/), version: 2.0.0
    Found link https://pypi.python.org/packages/c1/08/14df5ee08a1bce1598de4e1cdedb7e55e09060971a7241d40d15a1d7a14a/pydocstyle-1.1.1.zip#md5=4e2c692743e34adcce507479c8e76ebb (from https://pypi.python.org/simple/pydocstyle/), version: 1.1.1
    Found link https://pypi.python.org/packages/c8/ae/3177fa31d3e97a47ddb7c5871c398c056d9f06a31b8d6792e71e4bbf81d5/pydocstyle-1.1.1-py2.py3-none-any.whl#md5=72c612755d05e9cb6eb05d4c3ed5182b (from https://pypi.python.org/simple/pydocstyle/), version: 1.1.1
    Found link https://pypi.python.org/packages/fe/e6/e6ed14c372bd1ed58a19ef20e8f83a4ebbd1ecdbc9818f063be38189a5f6/pydocstyle-1.0.0-py2.py3-none-any.whl#md5=5adf95b7d25a60f05e7f8d9e5fddfb8b (from https://pypi.python.org/simple/pydocstyle/), version: 1.0.0
  Using version 2.1.0 (newest of versions: 1.0.0, 1.1.0, 1.1.1, 2.0.0, 2.1.0)
  Looking up "https://pypi.python.org/packages/21/1d/2afb75448d496a1a53815a5e2edd5fc8828eff6730ae29ce18801d2d4077/pydocstyle-2.1.0-py2.py3-none-any.whl" in the cache
  Current age based on date: 913
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 913
  Using cached pydocstyle-2.1.0-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/21/1d/2afb75448d496a1a53815a5e2edd5fc8828eff6730ae29ce18801d2d4077/pydocstyle-2.1.0-py2.py3-none-any.whl#md5=eeddf1eb4b069cb0a6ad8ff8c2cc07d9 (from https://pypi.python.org/simple/pydocstyle/)
Collecting snowballstemmer (from pydocstyle)
  1 location(s) to search for versions of snowballstemmer:
  * https://pypi.python.org/simple/snowballstemmer/
  Getting page https://pypi.python.org/simple/snowballstemmer/
  Looking up "https://pypi.python.org/simple/snowballstemmer/" in the cache
  Current age based on date: 195
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 195
  Analyzing links from page https://pypi.python.org/simple/snowballstemmer/
    Found link https://pypi.python.org/packages/0d/ed/2df260c89f15385f7e84f0957196897a70d3313d26a03bf4fc6f463cd4f5/snowballstemmer-1.1.0.tar.gz#md5=95a4beecbc9e45837da577c2e124c309 (from https://pypi.python.org/simple/snowballstemmer/), version: 1.1.0
    Found link https://pypi.python.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz#md5=643b019667a708a922172e33a99bf2fa (from https://pypi.python.org/simple/snowballstemmer/), version: 1.2.1
    Found link https://pypi.python.org/packages/76/6a/ef9df987c70c64ee7fea28da8608179ad0f44f3aaa390b4868c3aa39fb41/snowballstemmer-1.0.0.tar.gz#md5=e100e0f0a77d47504e041657fa54c4df (from https://pypi.python.org/simple/snowballstemmer/), version: 1.0.0
    Found link https://pypi.python.org/packages/a7/06/cce759f87ac50d6c7adc77e26cd4cd247a3dd632de31cf0f761dddb73aef/snowballstemmer-0.1.0.tar.gz#md5=db0164d2bece6622c1243cf2a4504331 (from https://pypi.python.org/simple/snowballstemmer/), version: 0.1.0
    Found link https://pypi.python.org/packages/bb/48/50528f822b5335a2f8155f4773bd49241129a0832469c2195710831755da/snowballstemmer-1.2.0.tar.gz#md5=51f2ef829db8129dd0f2354f0b209970 (from https://pypi.python.org/simple/snowballstemmer/), version: 1.2.0
    Found link https://pypi.python.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl#md5=198b60fa6a36d22c6c6f0b9304c6a40b (from https://pypi.python.org/simple/snowballstemmer/), version: 1.2.1
  Using version 1.2.1 (newest of versions: 0.1.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1)
  Looking up "https://pypi.python.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl" in the cache
  Current age based on date: 911
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 911
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl#md5=198b60fa6a36d22c6c6f0b9304c6a40b (from https://pypi.python.org/simple/snowballstemmer/)
Collecting six (from pydocstyle)
  1 location(s) to search for versions of six:
  * https://pypi.python.org/simple/six/
  Getting page https://pypi.python.org/simple/six/
  Looking up "https://pypi.python.org/simple/six/" in the cache
  Current age based on date: 195
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 195
  Analyzing links from page https://pypi.python.org/simple/six/
  Found link https://pypi.python.org/packages/02/c3/8e2a38edaac777ee2bbe479b3a65b020ade549efd6a224c2f4e95c818799/six-1.6.0.tar.gz#md5=eb22a24e8be9497dd71930bf2321b6ec (from https://pypi.python.org/simple/six/), version: 1.6.0
    Found link https://pypi.python.org/packages/02/f8/d16f06e49b0d2ef40548bf42826f926c8964ad3b1d00f8098dcc6ef15aea/six-1.3.0.tar.gz#md5=ec47fe6070a8a64c802363d2c2b1e2ee (from https://pypi.python.org/simple/six/), version: 1.3.0
    Found link https://pypi.python.org/packages/0b/5e/4b3f417a85d9cd30b172a1512a2d3cdd0ffb05a5deacb8adf2ef30db100d/six-1.5.1.tar.gz#md5=bb00c982fc0ec0dd6a760500b0941fa9 (from https://pypi.python.org/simple/six/), version: 1.5.1
    Found link https://pypi.python.org/packages/0e/f9/66471f9b7e9291cca697b2e61a10645a537f389a9d5c0679d50dd86b20f7/six-0.9.0.tar.gz#md5=5ce2947347101b9f54674c19ef88233d (from https://pypi.python.org/simple/six/), version: 0.9.0
    Found link https://pypi.python.org/packages/0f/dd/379fa572b72da0b482545116139529af8da92e686ea136271beecddd4e81/six-1.5.0.tar.gz#md5=72b33ff89f3b2f21dd2cb28fb94f7031 (from https://pypi.python.org/simple/six/), version: 1.5.0
    Found link https://pypi.python.org/packages/10/e3/a7f8eea80a9fa8358c1cd89ef489bc03675e69e54ed2982cd6f2a28d8295/six-1.9.0-py2.py3-none-any.whl#md5=9ac7e129a80f72d6fc1f0216f6e9627b (from https://pypi.python.org/simple/six/), version: 1.9.0
    Found link https://pypi.python.org/packages/11/3f/2b3c217c5427cdd12619024b1ee1b04d49e27fde5c29df2a0b92c26677c2/six-1.8.0.tar.gz#md5=1626eb24cc889110c38f7e786ec69885 (from https://pypi.python.org/simple/six/), version: 1.8.0
    Found link https://pypi.python.org/packages/16/64/1dc5e5976b17466fd7d712e59cbe9fb1e18bec153109e5ba3ed6c9102f1a/six-1.9.0.tar.gz#md5=476881ef4012262dfc8adc645ee786c4 (from https://pypi.python.org/simple/six/), version: 1.9.0
    Found link https://pypi.python.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz#md5=d12789f9baf7e9fb2524c0c64f1773f8 (from https://pypi.python.org/simple/six/), version: 1.11.0
    Found link https://pypi.python.org/packages/1b/2a/ad686ae156581a70a7be28e7762f7d956bec30d62dafe9295b78dc019692/six-1.7.1.tar.gz#md5=f9fbad970c6e855cabde7ec1144b9058 (from https://pypi.python.org/simple/six/), version: 1.7.1
    Found link https://pypi.python.org/packages/1d/8e/220ce5a36dac3aabccee871a34561ceba82ce14b53760143cf5e01bb4d2c/six-1.5.2.tar.gz#md5=322b86d0c50a7d165c05600154cecc0a (from https://pypi.python.org/simple/six/), version: 1.5.2
    Found link https://pypi.python.org/packages/20/0a/617bf23511160454995bf1cbe6789f22beeb8b49c1f3b1bbf4b5cd6a55ca/six-1.7.0-py2.py3-none-any.whl#md5=e5ca7e89cc79d755ea128fc7e2cb136e (from https://pypi.python.org/simple/six/), version: 1.7.0
    Found link https://pypi.python.org/packages/2b/4a/233721f6c6afeed5a2034f617f120fa646da935039f08e67ab8dc008a3e6/six-1.7.3.tar.gz#md5=784c6e5541c3c4952de9c0a966a0a80b (from https://pypi.python.org/simple/six/), version: 1.7.3
    Found link https://pypi.python.org/packages/2e/a4/6dcb84af409b7bc0c258a0d6bd7e14231724d9a46b750c048f09d74d870c/six-1.7.3-py2.py3-none-any.whl#md5=5f34fe522765d398b21decdce62ebd1d (from https://pypi.python.org/simple/six/), version: 1.7.3
    Found link https://pypi.python.org/packages/4e/02/f08545a99829a04e841b6443267f216629c723c23fb9cfd17c99c068e33a/six-0.9.1.tar.gz#md5=1b249e0011355722f569406135a8ac93 (from https://pypi.python.org/simple/six/), version: 0.9.1
    Found link https://pypi.python.org/packages/4e/aa/73683ca0c4237891e33562e3f55bcaab972869959b97b397637519d92035/six-1.4.1.tar.gz#md5=bdbb9e12d3336c198695aa4cf3a61d62 (from https://pypi.python.org/simple/six/), version: 1.4.1
    Found link https://pypi.python.org/packages/54/45/8b5eef1ba0b79acbdab01435359f37ae13dc6c4aafaa444b805e3867386d/six-1.6.0-py2.py3-none-any.whl#md5=e2755cf8a1d8e4eda44a8e3436c458ca (from https://pypi.python.org/simple/six/), version: 1.6.0
    Found link https://pypi.python.org/packages/54/d4/8f7d631f1c3defa2ff4bd7c3daddcc5ed6eb9df7631f3cf24cc376aa3231/six-1.1.0.tar.gz#md5=9e8099b57cd27493a6988e9c9b313e23 (from https://pypi.python.org/simple/six/), version: 1.1.0
    Found link https://pypi.python.org/packages/60/84/72c628d5a4efffb23e2fb46cdbf8ee669046d8208ba5dab08f989b7bfe9c/six-1.5.1-py2.py3-none-any.whl#md5=2064b715201fa76a55dea75675ee19f2 (from https://pypi.python.org/simple/six/), version: 1.5.1
    Found link https://pypi.python.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#md5=866ab722be6bdfed6830f3179af65468 (from https://pypi.python.org/simple/six/), version: 1.11.0
    Found link https://pypi.python.org/packages/6b/30/839b8059d1225dbd3a0dd97c3c370bbb978cde505e160b30515fb7be17d8/six-1.7.2-py2.py3-none-any.whl#md5=0e10f8d8e65257408e4428632859dad9 (from https://pypi.python.org/simple/six/), version: 1.7.2
    Found link https://pypi.python.org/packages/7e/16/792311d76b8e23da84e1b177fb973679de1c963391d0dcd7e963634bed4b/six-1.7.0.tar.gz#md5=92f7210da3db1e988979fa394aa41d7a (from https://pypi.python.org/simple/six/), version: 1.7.0
    Found link https://pypi.python.org/packages/8b/08/8f569ab2c81c1443ce43e29df2e7eec1ab7f005455f6c193793728b00f04/six-1.0b1.tar.gz#md5=cbfcc64af1f27162a6a6b5510e262c9d (from https://pypi.python.org/simple/six/), version: 1.0b1
    Found link https://pypi.python.org/packages/99/25/2df8760d6902620cfca85e36f07de491d14f2c325ecc01c1a5590d8af22d/six-1.4.0.tar.gz#md5=5fcab6a067b5ebf68ede2f4d02fe7547 (from https://pypi.python.org/simple/six/), version: 1.4.0
    Found link https://pypi.python.org/packages/a2/4b/2b4532b4eba116a02fc0b5e0b3540a073a61c003b7b6293b7b884afa8ff1/six-1.8.0-py2.py3-none-any.whl#md5=2f5f96148c68f3c1611f489678a8b445 (from https://pypi.python.org/simple/six/), version: 1.8.0
    Found link https://pypi.python.org/packages/a4/ed/a1410f4a3ae1492d87cbc7acdeea819db3caf6e526ef7032dd6fe50d2083/six-1.7.2.tar.gz#md5=4c26276583b01dfc73474cb32327af91 (from https://pypi.python.org/simple/six/), version: 1.7.2
    Found link https://pypi.python.org/packages/a6/af/4506a069312018665b8936e5d51b3aa013971ef65eab5231ef151a482dcd/six-1.0.0.tar.gz#md5=37c7ff036fdff2b1bb8d55e49ccb3b44 (from https://pypi.python.org/simple/six/), version: 1.0.0
    Found link https://pypi.python.org/packages/aa/ec/e6954e19e617c1b9860325f0995d456d8416c84a6cb9bce1c10998280b59/six-1.7.1-py2.py3-none-any.whl#md5=c3c1e251733acc9db947e75c9a02cf06 (from https://pypi.python.org/simple/six/), version: 1.7.1
    Found link https://pypi.python.org/packages/af/33/fa2097ac4bc7a9672517fdcb982bc7454fdd113f49f7ab353025b906a119/six-0.9.2.tar.gz#md5=92ea7c870396dd9222029a188c6bbd7f (from https://pypi.python.org/simple/six/), version: 0.9.2
    Found link https://pypi.python.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55 (from https://pypi.python.org/simple/six/), version: 1.10.0
    Found link https://pypi.python.org/packages/ba/19/aa48edcff9d0c396a4d009d362d0a0a1ac3db6f9d7d5736e0175b94d7ef8/six-1.6.1-py2.py3-none-any.whl#md5=ca195cc2271b03ae1c8750a88081c7f1 (from https://pypi.python.org/simple/six/), version: 1.6.1
    Found link https://pypi.python.org/packages/c7/a4/35520d20a8e4b3c28c9db705fffd4c7053e0236928951da32167e5078faa/six-1.5.2-py2.py3-none-any.whl#md5=ba32222ad0c5c7057a7c42e66e81289d (from https://pypi.python.org/simple/six/), version: 1.5.2
    Found link https://pypi.python.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl#md5=3ab558cf5d4f7a72611d59a81a315dc8 (from https://pypi.python.org/simple/six/), version: 1.10.0
    Found link https://pypi.python.org/packages/ca/15/e62a66024dded9640f8d39112330e6b108e7ab21a1b8618c2d1e2eea7e1d/six-1.5.0-py2.py3-none-any.whl#md5=3307efe2bc4ca8556befc9afe297c530 (from https://pypi.python.org/simple/six/), version: 1.5.0
    Found link https://pypi.python.org/packages/e8/70/b9c441d8c02b70eb3bf923c49944b8fc656f78a43c084d2a98534d7404e2/six-1.6.1.tar.gz#md5=07d606ac08595d795bf926cc9985674f (from https://pypi.python.org/simple/six/), version: 1.6.1
    Found link https://pypi.python.org/packages/e9/b4/0ccbc17cd49a812ab8363058bb12f0134cf2d3ba752391f309ddf567ae97/six-1.2.0.tar.gz#md5=2a5d1afc79912832ac78fd38e3d75d7e (from https://pypi.python.org/simple/six/), version: 1.2.0
  Using version 1.11.0 (newest of versions: 0.9.0, 0.9.1, 0.9.2, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.9.0, 1.10.0, 1.11.0)
  Looking up "https://pypi.python.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl" in the cache
  Current age based on date: 277643
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 277643
  Using cached six-1.11.0-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#md5=866ab722be6bdfed6830f3179af65468 (from https://pypi.python.org/simple/six/)
Installing collected packages: snowballstemmer, six, pydocstyle



  changing mode of mypath/temp/bin/pydocstyle to 755
Successfully installed pydocstyle-2.1.0 six-1.11.0 snowballstemmer-1.2.1
Cleaning up...
```

And `pip freeze` after installing:
```
pydocstyle==2.1.0
six==1.11.0
snowballstemmer==1.2.1
```

**Comment by ntarocco** [comment]
@Nurdok did you create the `whl` package on the right version? I have run it locally and I see  the `configparser` dependency in the `metadata.json`, but it is not there in the published version on `pypi`.

It would be nice if you can have a look to it quickly because it is blocking our continuos integration in many package (we need to install `configparser` manually on all our modules otherwise)

**Comment by Nurdok** [comment]
Hey guys, thanks for reporting this. I'll try to get to fix this ASAP.

**Comment by Nurdok** [comment]
@ntarocco what happened was that until this version, pydocstyle had a universal wheel, and I forgot to account for this change.

**Comment by Nurdok** [comment]
@tpazderka @ntarocco 
I uploaded version 2.1.1 to PyPI that should fix this issue. Let me know if it works on your end. However, as a general note, I do recommend pinning down dependencies in CI builds to make the build deterministic and reproducible.
