### ISSUE TITLE
Exception in case file lacks newline at end of file

### ISSUE THREAD

**Issue by languitar** [PyCQA/pydocstyle#321]
Attached is a file that makes pydocstyle crash because it lacks a trailing newline.

```
Traceback (most recent call last):
  File "/home/languitar/src/autosuspend/.tox/check/bin/pydocstyle", line 11, in <module>
    sys.exit(main())
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/cli.py", line 68, in main
    sys.exit(run_pydocstyle())
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/cli.py", line 45, in run_pydocstyle
    ignore_decorators=ignore_decorators))
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/checker.py", line 703, in check
    ignore_decorators):
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/checker.py", line 64, in check_source
    module = parse(StringIO(source), filename)
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/parser.py", line 305, in __call__
    return self.parse(*args, **kwargs)
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/parser.py", line 300, in parse
    return self.parse_module()
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/parser.py", line 451, in parse_module
    children = list(self.parse_definitions(Module, all=True))
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/parser.py", line 401, in parse_definitions
    yield self.parse_definition(class_._nest(self.current.value))
  File "/home/languitar/src/autosuspend/.tox/check/lib/python3.6/site-packages/pydocstyle/parser.py", line 513, in parse_definition
    class_.__name__, name, self.current.kind,
AttributeError: 'NoneType' object has no attribute 'kind'
```
[test.py.txt](https://github.com/PyCQA/pydocstyle/files/2084570/test.py.txt)

**Comment by shacharoo** [comment]
Fixed by #336. Thanks!
