### ISSUE TITLE
With Python 3.10, ImportError: cannot import name 'Set' from 'collections' 

### ISSUE THREAD

**Issue by philvarner** [PyCQA/pydocstyle#590]
When running this via pre-commit under Python 3.10 using

```
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: '.*(test|alembic|scripts).*'
```

I get the error:

```
Verifying PEP257 Compliance..............................................Failed
- hook id: pydocstyle
- exit code: 1

Traceback (most recent call last):
  File "/Users/philvarner/.cache/pre-commit/repo54n9enag/py_env-python3.10/bin/pydocstyle", line 5, in <module>
    from pydocstyle.cli import main
  File "/Users/philvarner/.cache/pre-commit/repo54n9enag/py_env-python3.10/lib/python3.10/site-packages/pydocstyle/__init__.py", line 1, in <module>
    from .checker import check
  File "/Users/philvarner/.cache/pre-commit/repo54n9enag/py_env-python3.10/lib/python3.10/site-packages/pydocstyle/checker.py", line 12, in <module>
    from .config import IllegalConfiguration
  File "/Users/philvarner/.cache/pre-commit/repo54n9enag/py_env-python3.10/lib/python3.10/site-packages/pydocstyle/config.py", line 6, in <module>
    from collections import Set, namedtuple
ImportError: cannot import name 'Set' from 'collections' (/Users/philvarner/.pyenv/versions/3.10.3/lib/python3.10/collections/__init__.py)
```

**Comment by philvarner** [comment]
Sorry, this was coming from a very old version of https://github.com/chewse/pre-commit-mirrors-pydocstyle that was also in the precommit file.
